book_club/book_club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html")), 
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('books/',include('books.urls')),
]

book_club/books/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from .views import (BookCreateView, GenreListView, GenreDetailView, AuthorCreateView, LogoutView)

app_name = 'books'
from django.contrib import admin
urlpatterns = [
    path('', views.GenreListView.as_view(), name='genre_list'),
    path('admin/', admin.site.urls,),
    path('accounts/', include('django.contrib.auth.urls')),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('book/<int:pk>/delete/', views.BookDeleteView.as_view, name='book_delete'),
    path('book/<int:pk>/edit/', views.BookUpdateView.as_view(), name='book_update'),
    path('genre/<int:pk>/', views.GenreDetailView.as_view(), name='genre_detail'),
    path('genre/<int:pk>/add-book/', views.BookCreateView.as_view(), name='book_create'),
    path('author/new/', views.AuthorCreateView.as_view(), name='author_create'),
    path('authors/', views.AuthorListView.as_view(), name='author_list'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path("logout/", views.LogoutView.as_view(), name = "logout"),
]

book_club/books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings

class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=200)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books:author_list') 

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    genres = models.ManyToManyField(Genre)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField(null=True, blank=True)  # New field added
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('books:genre_detail', args=[str(self.id)])


# Create your models here.

book_club/books/views.py
from django import forms
from django.utils.http import urlencode
from django.shortcuts import render, redirect
from django.views import generic, View
from .models import Book, Genre, Author
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from books.owner import OwnerListView, OwnerCreateView, OwnerDetailView, OwnerUpdateView, OwnerDeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, get_object_or_404

# Create your views here.
class GenreListView(generic.ListView):
    model = Genre
    template_name = 'books/genre_list.html'
    context_object_name = 'genres'

class GenreDetailView(generic.DetailView):
    model = Genre
    template_name = 'books/genre_detail.html'
    context_object_name = 'genre'

class BookCreateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'genres', 'rating']

    author = forms.ModelChoiceField(queryset=Author.objects.all())
    genres = forms.ModelMultipleChoiceField(queryset=Genre.objects.all())

class BookCreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Book
    form_class = BookCreateForm
    template_name = 'books/book_form.html'
    success_url = reverse_lazy("books:genre_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Assign the current user as the owner of the book
        return super().form_valid(form)

class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book
    template_name = 'books/book_detail.html'
    context_object_name = 'book'
    success_url = reverse_lazy("books:genre_list")


class BookDeleteView(OwnerDeleteView):
    model = Book
    template_name = 'books/book_confirm_delete.html'
    context_object_name = 'book'
    fields = '__all__'
    success_url = reverse_lazy("books:genre_list")  # Redirect after successful deletion

class BookUpdateView(OwnerUpdateView):
    model = Book
    fields = ['title', 'author', 'genres', 'rating']
    template_name = 'books/book_form.html'
    context_object_name = 'book'

    def get_success_url(self):
        return reverse_lazy('books:book_detail', kwargs={'pk': self.object.pk})
    
class AuthorCreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Author
    fields = ['name']
    template_name = 'books/author_form.html'
    fields = '__all__'
    success_url = reverse_lazy("books:genre_list")  # Redirect to the list of authors after successful creation

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Set the owner to the current logged-in user
        return super().form_valid(form)
    
class AuthorListView(generic.ListView):
    model = Author
    template_name = 'books/author_list.html'
    context_object_name = 'authors'
    fields = '__all__'
    success_url = reverse_lazy("books:genre_list")

class LogoutView(View):
    def get(self, request):
        logout(request)
        return render(request, 'registration/logout.html')


class DumpPython(View):
    def get(self, req):
        resp = "<pre>\nUser Data in Python:\n\n"
        resp += "Login url: " + reverse('books:login') + "\n"
        resp += "Logout url: " + reverse('books:logout') + "\n\n"

        if req.user.is_authenticated:
            resp += "User " + req.user.username + "\n"
        else:
            resp += "User is not logged in\n"
        
        resp += """<a href="/books">Go back</a>"""
        return HttpResponse(resp)

class ManualProtect(View):
    def get(self, request):
        if request.user.is_authenticated:
            return render(request, 'books/authentication.html')
        loginurl = reverse('login')+'?'+urlencode({'next': request.path})
        return redirect(loginurl)
    
class ProtectView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'books/authentication.html')
        

book_club/books/templates/books/authentication.html
{% if user.is_authenticated %}
<p>Authenticated    
<pre>
    Name: {{ user.get_full_name }}
    ID: {{ user.id }}
</pre>
</p>
<p>You can <a href="{% url 'books:logout' %}?next={{ 'books:logout' }}">Logout</a> if you like</p>
<p>Want to go <a href="{% url 'books:genre_list' %}">Back?</a></p>
{% else %}
<p>You are not logged in</p>
<p>You can <a href="{% url 'login' %}?next={{ request.path }}">Login</a> if you like</p>
{% endif %}

book_club/books/templates/books/author_form.html
{% extends 'base.html' %}

{% block content %}
<h2>Add a New Author</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
<a href="{% url 'books:genre_list' %}">Back to Genres</a>
{% endblock %}

book_club/books/templates/books/author_list.html
{% extends 'base.html' %}

{% block content %}
    <h2>List of Authors</h2>
    <a href="{% url 'books:author_create' %}">Add a New Author</a>
    <ul>
        {% for author in authors %}
            <li>{{ author.name }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'books:genre_list' %}">Back to Genres</a>
{% endblock %}

book_club/books/templates/books/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Library App{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

book_club/books/templates/books/book_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h2>Are you sure you want to delete the book: "{{ book.title }}"?</h2>

  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
  </form>

  <a href="{% url 'books:genre_list' %}">Cancel</a>
{% endblock %}

book_club/books/templates/books/book_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ book.title }}</h2>
    <a href="{% url 'books:book_update' book.pk %}">Edit Book</a>
    <p><strong>Author:</strong> {{ book.author }}</p>
    
    <p><strong>Genres:</strong> 
        {% for genre in book.genres.all %}
            {{ genre.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <p><strong>Rating:</strong> {{ book.rating }}/10</p>

    <p><a href="{% url 'books:genre_detail' book.genres.first.pk %}">Back to Genre</a></p>
    <p><a href="{% url 'books:book_delete' book.pk %}">Delete Book</a></p>
{% endblock %}

book_club/books/templates/books/book_form.html
{% extends 'base.html' %}

{% block content %}
<h2>Add a Book</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
<a href="{% url 'books:genre_list'%}">Back to Genres</a>

<p>Don't see the author? <a href="{% url 'books:author_create' %}">Add a New Author</a></p>
{% endblock %}

book_club/books/templates/books/genre_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ genre.name }}</h2>
<a href="{% url 'books:book_create' genre.pk %}">Add a Book</a>
<h3>Books in this Genre:</h3>
<ul>
    {% for book in genre.book_set.all %}
        <li><a href="{% url 'books:book_detail' book.pk %}">{{ book.title }} by {{ book.author }}</a></li>
    {% endfor %}
</ul>


<a href="{% url 'books:genre_list'%}">Back to Genres</a>
{% endblock %}

book_club/books/templates/books/genre_list.html
{% extends 'base.html' %}

{% block content %}
<h2>Genres</h2>
<ul>
    {% for genre in genres %}
        <li>
            <a href="{% url 'books:genre_detail' genre.pk %}">{{ genre.name }}</a>
        </li>
    {% endfor %}
</ul>

{% if user.is_authenticated %}
    <a href="{% url 'books:logout' %}?next={% url 'books:genre_list' %}">Logout</a>
{% endif %}
{% endblock %}

book_club/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Lary Django Projects{% endblock %}</title>
    <link href="{% static 'base.css' %}" rel="stylesheet">
    <script src="{% static 'init.js' %}"></script>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

book_club/templates/home.html
{% extends 'base.html' %}

{% block content %}


<h1>Lary's Django Projects</h1>

<main>
<ul>
  <li><a href="books/">Books App</a></li>

</ul>
</main>
    {% endblock %}